# Generated by Django 3.0.6 on 2020-07-27 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.TextField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('mobile_token', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('roomname', models.TextField()),
                ('guid', models.TextField(max_length=255)),
                ('capacity_limit', models.IntegerField(default=5)),
                ('host_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='api.Users')),
                ('participants', models.ManyToManyField(blank=True, to='api.Users')),
            ],
        ),
    ]
