# Generated by Django 3.0.6 on 2020-07-27 12:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('mobile_token', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('roomname', models.CharField(blank=True, max_length=20)),
                ('capacity_limit', models.IntegerField(blank=True, default=5)),
                ('host_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='api.Users')),
                ('participants', models.ManyToManyField(blank=True, to='api.Users')),
            ],
        ),
    ]
